//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, NSCache, NSString;

@interface WAAsynchronousAssetLoader : NSObject
{
    NSCache *_resourceCache;
    NSString *_assetExtension;
    NSBundle *_weatherFrameworkBundle;
}

+ (id)sharedAssetLoader;
@property(retain, nonatomic) NSBundle *weatherFrameworkBundle; // @synthesize weatherFrameworkBundle=_weatherFrameworkBundle;
@property(copy, nonatomic) NSString *assetExtension; // @synthesize assetExtension=_assetExtension;
@property(retain, nonatomic) NSCache *resourceCache; // @synthesize resourceCache=_resourceCache;
- (void)dealloc;
- (struct CGImage *)CAMLParser:(id)arg1 resourceForURL:(id)arg2;
- (void)CAMLParser:(id)arg1 didLoadResource:(struct CGImage *)arg2 fromURL:(id)arg3;
- (id)gradientLayerForCondition:(int)arg1 isDay:(_Bool)arg2;
- (void)getColors:(id *)arg1 locations:(id *)arg2 condition:(int)arg3 isDay:(int)arg4;
- (struct CGColor *)colorWithDictionary:(id)arg1;
- (void)prepareLayer:(id)arg1 clearLayers:(id)arg2 hiddenLayers:(id)arg3;
- (id)rootLayerForFile:(id)arg1;
- (id)rootLayerForCondition:(int)arg1 isDay:(_Bool)arg2;
- (id)rootLayerForCondition:(int)arg1 isDay:(_Bool)arg2 clearLayers:(id)arg3 hiddenLayers:(id)arg4;
- (id)rootLayerForOverlayCondition:(int)arg1 isDay:(_Bool)arg2;
- (id)init;
- (id)filenameForCondition:(int)arg1 isDay:(_Bool)arg2;
- (id)nameForCondition:(int)arg1 isDay:(_Bool)arg2;
- (id)nameForCondition:(int)arg1;

@end

