//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, CALayer, SBFStaticWallpaperView;

@interface WADynamicWeatherBackground : UIView
{
    _Bool _isOverlay;
    _Bool _isDay;
    int _variant;
    int _condition;
    CALayer *_conditionLayer;
    CAGradientLayer *_gradientLayer;
    SBFStaticWallpaperView *_wallpaperView;
    UIView *_rootView;
}

+ (id)backgroundWithCondition:(int)arg1 isDay:(_Bool)arg2 clearLayers:(id)arg3 hiddenLayers:(id)arg4 variant:(int)arg5;
+ (id)backgroundWithCondition:(int)arg1 isDay:(_Bool)arg2;
@property(nonatomic) _Bool isDay; // @synthesize isDay=_isDay;
@property(nonatomic) int condition; // @synthesize condition=_condition;
@property(retain, nonatomic) UIView *rootView; // @synthesize rootView=_rootView;
@property(retain, nonatomic) SBFStaticWallpaperView *wallpaperView; // @synthesize wallpaperView=_wallpaperView;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) CALayer *conditionLayer; // @synthesize conditionLayer=_conditionLayer;
@property(nonatomic) int variant; // @synthesize variant=_variant;
@property(nonatomic) _Bool isOverlay; // @synthesize isOverlay=_isOverlay;
- (void)dealloc;
- (void)pause;
- (void)resume;
- (void)addSublayer:(id)arg1;
- (_Bool)hasSublayer:(id)arg1;
- (void)setCondition:(int)arg1 isDay:(_Bool)arg2;
- (void)layoutConditionLayer:(id)arg1;
- (void)initializeRootViewWithBounds:(struct CGRect)arg1;
- (void)updateGradientWithCondition:(int)arg1 isDay:(_Bool)arg2;
- (id)wallpaperViewWithBounds:(struct CGRect)arg1 variant:(int)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(id)arg1;
- (id)initWithCondition:(int)arg1 isDay:(_Bool)arg2 clearLayers:(id)arg3 hiddenLayers:(id)arg4 variant:(int)arg5;
- (id)initWithCondition:(int)arg1 isDay:(_Bool)arg2;

@end

