//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAImageWrapper : NSObject
{
    struct CGImage *_image;
}

+ (id)wrapperWithCGImage:(struct CGImage *)arg1;
@property(nonatomic) struct CGImage *image; // @synthesize image=_image;
- (void)dealloc;
- (id)initWithCGImage:(struct CGImage *)arg1;

@end

