//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface WBWallpaperController : NSObject
{
    _Bool _loaded;
    NSMutableDictionary *_preferences;
}

+ (id)sharedInstance;
+ (id)preferencesPath;
@property(retain, nonatomic) NSMutableDictionary *preferences; // @synthesize preferences=_preferences;
@property(nonatomic) _Bool loaded; // @synthesize loaded=_loaded;
- (void)dealloc;
- (void)writePreferencesToFile:(id)arg1;
- (void)clearSharedWallpaper;
- (void)clearHomeScreenWallpaper;
- (void)clearLockScreenWallpaper;
- (void)setWallpaper:(id)arg1 withUserInfo:(id)arg2;
- (void)updateSettingsForCondition:(int)arg1 isDay:(_Bool)arg2 forVariant:(int)arg3;
- (void)updateCondition:(int)arg1 isDay:(_Bool)arg2 forVariant:(int)arg3;
- (id)init;
- (id)wallpaperSettingsForVariant:(int)arg1;
@property(nonatomic) float updateInterval;
- (_Bool)variantsShareWallpaper:(_Bool)arg1;
- (_Bool)variantsShareWallpaper;

@end

