/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
#import "EKCalendarDate.h"


@class CalendarEventLoader, EKCalendarDate, EKEvent, EKEventStore, NSArray, NSCalendar, NSLock, NSSet, NSString, _EKNotificationMonitor;

@interface CalendarModel : NSObject

@property (nonatomic,retain) NSSet * selectedCalendars;

- (id)occurrencesForDay:(id)arg1 waitForLoad:(BOOL)arg2;
- (void)addOccurrenceAwaitingDeletion:(id)arg1;
- (id)occurrencesForStartDate:(id)arg1 endDate:(id)arg2 preSorted:(BOOL)arg3 waitForLoad:(BOOL)arg4;
- (id)occurrencesForStartDay:(id)arg1 endDay:(id)arg2 preSorted:(BOOL)arg3 waitForLoad:(BOOL)arg4;
- (void)setMaxCachedDays:(unsigned)arg1;

@property(readonly, nonatomic) EKCalendarDate *selectedDay;
- (id)init;

@end
