/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

 #import <Foundation/NSObject.h>

@interface EKCalendarDate : NSObject

+ (id)calendarDateWithAbsoluteTime:(double)arg1 timeZone:(id)arg2;
+ (id)calendarDateWithDate:(id)arg1 timeZone:(id)arg2;
+ (id)calendarDateWithDateComponents:(id)arg1 timeZone:(id)arg2;

- (double)absoluteTime;
- (id)calendarDateByAddingDays:(long long)arg1;
- (id)calendarDateByAddingMonths:(long long)arg1;
- (id)calendarDateByAddingWeeks:(long long)arg1;
- (id)calendarDateByAddingYears:(long long)arg1;
- (id)calendarDateForDay;
- (id)calendarDateForEndOfDay;
- (id)calendarDateForEndOfMonth;
- (id)calendarDateForEndOfWeekWithWeekStart:(int)arg1;
- (id)calendarDateForMonth;
- (id)calendarDateForWeekWithWeekStart:(int)arg1;
- (id)calendarDateForYear;
- (id)calendarDateInTimeZone:(id)arg1;
- (id)calendarDateWithDate:(id)arg1;
- (long long)compare:(id)arg1;
- (id)components;
- (id)componentsIncludingTime:(bool)arg1;
- (id)componentsWithoutTime;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)date;
- (unsigned long long)day;
- (int)dayOfWeek;
- (unsigned long long)dayOfYear;
- (unsigned long long)daysInMonth;
- (unsigned long long)daysInYear;
- (id)description;
- (long long)differenceInDays:(id)arg1;
- (long long)differenceInMonths:(id)arg1;
- (long long)differenceInYears:(id)arg1;
- (id)earlierDate:(id)arg1;
- (unsigned long long)hour;
- (id)initWithAbsoluteTime:(double)arg1 internalTimeZone:(id)arg2;
- (id)initWithAbsoluteTime:(double)arg1 timeZone:(id)arg2;
- (id)initWithDate:(id)arg1 timeZone:(id)arg2;
- (id)initWithDateComponents:(id)arg1 timeZone:(id)arg2;
- (bool)isEqual:(id)arg1;
- (id)laterDate:(id)arg1;
- (unsigned long long)minute;
- (unsigned long long)month;
- (double)second;
- (long long)secondsFromGMT;
- (id)timeZone;
- (unsigned long long)weekOfYear;
- (unsigned long long)weeksInYear;
- (unsigned long long)year;

@end