# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iDownloadBlog' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iDownloadBlog

  pod 'AFNetworking', '~> 2.0'
  pod 'SDFeedParser', '~> 1.0'
end
