//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface FCCurrentWeatherView : UIView
{
    _Bool day;
    _Bool celsius;
    NSString *temperature;
    unsigned long long conditionCode;
    NSString *high;
    NSString *low;
    long long alignment;
}

@property(nonatomic) long long alignment; // @synthesize alignment;
@property(getter=isCelsius) _Bool celsius; // @synthesize celsius;
@property(getter=isDay) _Bool day; // @synthesize day;
@property(retain, nonatomic) NSString *low; // @synthesize low;
@property(retain, nonatomic) NSString *high; // @synthesize high;
@property unsigned long long conditionCode; // @synthesize conditionCode;
@property(retain, nonatomic) NSString *temperature; // @synthesize temperature;
- (void)updateForCity:(id)arg1 animated:(_Bool)arg2;
- (void)drawRect:(struct CGRect)arg1;

@end

