//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSString;

@interface FCDailyForecastView : UIView
{
    _Bool celsius;
    _Bool day;
    NSArray *dayForecasts;
    unsigned long long conditionCode;
    NSString *temperature;
    NSString *location;
}

@property(getter=isDay) _Bool day; // @synthesize day;
@property(retain, nonatomic) NSString *location; // @synthesize location;
@property(retain, nonatomic) NSString *temperature; // @synthesize temperature;
@property unsigned long long conditionCode; // @synthesize conditionCode;
@property(retain, nonatomic) NSArray *dayForecasts; // @synthesize dayForecasts;
@property(getter=isCelsius) _Bool celsius; // @synthesize celsius;
- (void)drawRect:(struct CGRect)arg1;

@end

