//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "LPPage.h"
#import "UIAlertViewDelegate.h"

@class FCDailyForecastView, FCHourlyForecastView, NSString, UIScrollView;

@interface FCForecastViewController : UIViewController <LPPage, UIAlertViewDelegate>
{
    _Bool _configureAlertShown;
    FCHourlyForecastView *hourlyView;
    UIScrollView *hourlyScrollView;
    FCDailyForecastView *dailyView;
}

@property(retain, nonatomic) FCDailyForecastView *dailyView; // @synthesize dailyView;
@property(retain, nonatomic) UIScrollView *hourlyScrollView; // @synthesize hourlyScrollView;
@property(retain, nonatomic) FCHourlyForecastView *hourlyView; // @synthesize hourlyView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)isTimeEnabled;
- (double)backgroundAlpha;
- (double)idleTimerInterval;
- (long long)priority;
- (void)loadView;
- (void)updateForCity:(id)arg1 animated:(_Bool)arg2;
- (void)_animateDisplayOfView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

