//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@interface FCForecastSettings : NSMutableDictionary
{
}

+ (id)settings;
+ (void)initialize;
+ (void)reloadSettings;
- (_Bool)fullSizeClock;
- (_Bool)showSlideToUnlock;
- (_Bool)showTimeOnForecast;
- (int)updateInterval;
- (_Bool)darkenForecast;
- (_Bool)darkenCurrentWeather;
- (_Bool)animateWallpaper;
- (_Bool)adjustWallpaperDimming;
- (_Bool)showHomescreenWallpaper;
- (_Bool)showLockscreenWallpaper;
- (_Bool)hideDescription;
- (_Bool)showForecast;
- (_Bool)showCurrentWeatherInClock;
- (_Bool)showCurrentWeatherAtBottom;
- (int)showCurrentWeather;
- (int)intForKey:(id)arg1 withDefault:(int)arg2;
- (_Bool)boolForKey:(id)arg1 withDefault:(_Bool)arg2;

@end

