//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSDateFormatter;

@interface FCHourlyForecastView : UIView
{
    NSDateFormatter *_fromHourlyFormatter;
    _Bool celsius;
    NSArray *hourlyForecasts;
}

@property(getter=isCelsius) _Bool celsius; // @synthesize celsius;
@property(retain, nonatomic) NSArray *hourlyForecasts; // @synthesize hourlyForecasts;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

