//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFProceduralWallpaper.h"

@class CALayer, NSCache, NSDictionary, NSObject<OS_dispatch_queue>, UIColor;

@interface FCWeatherWallpaper : SBFProceduralWallpaper
{
    NSObject<OS_dispatch_queue> *_updateQueue;
    CALayer *_backgroundLayer;
    CALayer *_overlayContainerLayer;
    NSDictionary *_camlClasses;
    NSCache *_cachedResources;
    NSCache *_cachedLayers;
    long long _currentConditionCode;
    _Bool _currentlyDay;
    UIColor *averageColor;
    CALayer *overlay;
    id <SBFProceduralWallpaperDelegate> delegate;
}

+ (_Bool)colorChangesSignificantly;
+ (id)representativeThumbnailImageName;
+ (id)thumbnailImageName;
+ (id)identifier;
@property(retain, nonatomic) id <SBFProceduralWallpaperDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) CALayer *overlay; // @synthesize overlay;
@property(retain, nonatomic) UIColor *averageColor; // @synthesize averageColor;
- (void)setAnimating:(_Bool)arg1;
- (id)view;
- (void)updateForCity:(id)arg1 animated:(_Bool)arg2;
- (id)filenameForCode:(long long)arg1 isDay:(_Bool)arg2;
- (id)parseLayer:(id)arg1;
- (id)CAMLParser:(id)arg1 resourceForURL:(id)arg2;
- (Class)CAMLParser:(id)arg1 didFailToFindClassWithName:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

