//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Forecast)
+ (id)forecastImageTemplateNamed:(id)arg1;
+ (id)forecastImageNamed:(id)arg1;
+ (id)weatherImageTemplateNamed:(id)arg1;
+ (id)weatherImageNamed:(id)arg1;
- (id)imageWithOverlayColor:(id)arg1;
@end

