/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

//#import "SBIconIndexNode.h"

@class NSHashTable, UIImage;

@interface SBIcon : NSObject
{
    NSHashTable *_observers;
    id _badgeNumberOrString;
    unsigned int _uninstalled:1;
    UIImage *_cachedIconImages[14];
}

+ (id)memoryMappedIconImageOfSize:(struct CGSize)arg1 scale:(float)arg2 withDrawing:(id)arg3;
+ (id)memoryMappedIconImageForIconImage:(id)arg1;
+ (id)_iconImageOfSize:(struct CGSize)arg1 scale:(float)arg2 failGracefully:(BOOL)arg3 drawing:(id)arg4;
+ (id)_iconImagesMemoryPool;
- (BOOL)canReceiveGrabbedIcon;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (BOOL)isUninstalled;
- (void)setUninstalled;
- (void)completeUninstall;
- (BOOL)allowsUninstall;
- (BOOL)progressIsPaused;
- (float)progressPercent;
- (int)progressState;
- (void)launchFromLocation:(int)arg1;
- (id)automationID;
- (BOOL)isRecentlyUpdated;
- (void)setBadge:(id)arg1;
- (void)noteBadgeDidChange;
- (int)accessoryTypeForLocation:(int)arg1;
- (id)accessoryTextForLocation:(int)arg1;
- (id)badgeNumberOrString;
- (int)badgeValue;
- (void)reloadIconImagePurgingImageCache:(BOOL)arg1;
- (void)reloadIconImage;
- (void)purgeCachedImages;
- (id)gridCellImage;
- (id)getGenericIconImage:(int)arg1;
- (id)getUnmaskedIconImage:(int)arg1;
- (id)getIconImage:(int)arg1;
- (id)getStandardIconImageForLocation:(int)arg1;
- (BOOL)shouldCacheImageForFormat:(int)arg1;
- (id)generateIconImage:(int)arg1;
- (BOOL)launchEnabled;
- (id)tags;
- (BOOL)matchesEntity:(id)arg1;
- (int)localizedCompareDisplayNames:(id)arg1;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (void)localeChanged;
- (BOOL)matchesRepresentation:(id)arg1;
- (id)representation;
- (void)dealloc;
- (id)init;
- (int)iconFormatForLocation:(int)arg1;
@property(readonly, nonatomic) BOOL shouldWarmUp;
- (BOOL)hasCachedImageForLocation:(int)arg1;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(unsigned int)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (BOOL)hasObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)description;
- (id)application;
- (BOOL)isApplicationIcon;
- (BOOL)isBookmarkIcon;
- (id)appPlaceholder;
- (BOOL)isDownloadingIcon;
- (BOOL)isUserInstalledApplicationIcon;
- (BOOL)isWebApplicationIcon;
- (BOOL)hasFolderIconView;
- (id)folder;
- (BOOL)isFolderIcon;
- (id)applicationBundleID;
- (id)webClip;
- (id)leafIdentifier;
- (BOOL)isLeafIcon;
- (Class)iconImageViewClassForLocation:(int)arg1;
- (Class)iconViewClassForLocation:(int)arg1; // This allows us to inject our own shite
- (void)_notifyLaunchEnabledDidChange;
- (void)_notifyAccessoriesDidUpdate;
- (void)_notifyImageDidUpdate;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isNewsstandApplicationIcon;
- (BOOL)isNewsstandIcon;
- (BOOL)isEmptyPlaceholder;
- (BOOL)isGrabbedIconPlaceholder;
- (BOOL)isPlaceholder;

@end

