/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "SBIconObserver-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"
#import "SBIconViewDelegate-Protocol.h"
#import "SBIconViewObserver-Protocol.h"

@interface _UILegibilityView : UIView
@end

@class NSTimer, SBCloseBoxView, SBFParallaxSettings, SBFolderIconBackgroundView, SBIcon, SBIconImageCrossfadeView, SBIconImageView, _UILegibilitySettings, _UILegibilityView;

@interface SBIconView : UIView <_UISettingsKeyObserver, SBIconObserver>
{
    SBIcon *_icon;
    int _iconLocation;
    UIView *_currentImageView;
    SBIconImageView *_iconImageView;
    SBIconImageCrossfadeView *_crossfadeView;
    UIView/*<SBIconAccessoryView>*/ *_accessoryView;
    SBCloseBoxView *_closeBox;
    SBFParallaxSettings *_closeBoxParallaxSettings;
    struct CGPoint _wallpaperRelativeCloseBoxCenter;
    _UILegibilityView *_labelView;
    UIView *_updatedMark;
    SBFolderIconBackgroundView *_dropGlow;
    unsigned int _drawsLabel:1;
    unsigned int _isEditing:1;
    unsigned int _isPaused:1;
    unsigned int _isGrabbed:1;
    unsigned int _isOverlapping:1;
    unsigned int _refusesRecipientStatus:1;
    unsigned int _highlighted:1;
    unsigned int _launchDisabled:1;
    unsigned int _isJittering:1;
    unsigned int _allowJitter:1;
    unsigned int _touchDownInIcon:1;
    unsigned int _hideLabel:1;
    unsigned int _hideUpdatedMark;
    struct CGPoint _unjitterPoint;
    struct CGPoint _grabPoint;
    NSTimer *_longPressTimer;
    struct CGRect _visibleImageRect;
    id <SBIconViewDelegate> _delegate;
    id <SBIconViewObserver> _observer;
    _UILegibilitySettings *_legibilitySettings;
    float _iconImageAlpha;
    float _iconAccessoryAlpha;
    float _iconLabelAlpha;
    struct CGPoint _wallpaperRelativeImageCenter;
}

+ (id)_jitterTransformAnimation;
+ (id)_jitterPositionAnimation;
+ (struct CGSize)maxLabelSize;
+ (struct CGRect)_rectForLayoutMetric:(int)arg1;
+ (struct CGSize)defaultVisibleIconImageSize;
+ (struct CGPoint)defaultIconImageCenter;
+ (CGSize)defaultIconImageSize;
+ (float)_labelHeight;
+ (struct CGSize)defaultIconSize;
+ (float)updatedMarkRightMargin;
+ (BOOL)canShowUpdatedMark;
+ (int)_defaultIconFormat;
@property(nonatomic) struct CGPoint wallpaperRelativeImageCenter; // @synthesize wallpaperRelativeImageCenter=_wallpaperRelativeImageCenter;
@property(nonatomic) float iconLabelAlpha; // @synthesize iconLabelAlpha=_iconLabelAlpha;
@property(nonatomic) float iconAccessoryAlpha; // @synthesize iconAccessoryAlpha=_iconAccessoryAlpha;
@property(nonatomic) float iconImageAlpha; // @synthesize iconImageAlpha=_iconImageAlpha;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) int location; // @synthesize location=_iconLocation;
@property(nonatomic) id <SBIconViewObserver> observer; // @synthesize observer=_observer;
@property(nonatomic) id <SBIconViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILongPressGestureRecognizer *shortcutMenuPeekGesture; // iOS 9
@property(retain, nonatomic) SBIcon *icon;
- (void)iconLaunchEnabledDidChange:(id)arg1;
- (void)iconAccessoriesDidUpdate:(id)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_updateProgressAnimated:(BOOL)arg1;
- (void)prepareForRecycling;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (BOOL)_delegateTapAllowed;
- (void)_delegateTouchEnded:(BOOL)arg1;
- (struct UIEdgeInsets)snapshotEdgeInsets;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_closeBoxTapped;
- (BOOL)_isShowingCloseBox;
- (void)_updateCloseBoxAnimated:(BOOL)arg1;
- (void)_applyEditingStateAnimated:(BOOL)arg1;
@property(nonatomic) BOOL isEditing;
- (void)setIsEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setTouchDownInIcon:(BOOL)arg1;
- (BOOL)isTouchDownInIcon;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)cancelLongPressTimer;
- (void)longPressTimerFired;
- (void)cleanupAfterImageCrossfade;
- (void)setImageCrossfadeMorphFraction:(float)arg1;
- (void)setImageCrossfadeFadeFraction:(float)arg1;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3 anchorPoint:(struct CGPoint)arg4;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3;
- (id)dropGlow;
- (void)removeDropGlow;
- (void)showDropGlow:(BOOL)arg1;
- (void)prepareDropGlow;
- (void)setIsOverlapping:(BOOL)arg1;
- (BOOL)isGrabbed;
- (void)setIsGrabbed:(BOOL)arg1;
- (double)grabDurationForEvent:(id)arg1;
- (BOOL)canReceiveGrabbedIcon:(id)arg1;
- (void)setRefusesRecipientStatus:(BOOL)arg1;
- (void)setIconPosition:(struct CGPoint)arg1;
- (void)removeAllIconAnimations;
- (void)setAllowJitter:(BOOL)arg1;
- (void)_updateJitter;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)isInDock;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)isHighlighted;
- (BOOL)allowsTapWhileEditing;
- (void)_updateBrightness;
- (BOOL)pointMostlyInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)_automationID;
- (void)_createAccessoryViewIfNecessary;
- (void)_updateAccessoryViewWithAnimation:(BOOL)arg1;
- (void)_updateIconImageViewAnimated:(BOOL)arg1;
- (void)_updateUpdatedMark;
- (id)_legibilitySettingsWithPrimaryColor:(id)arg1;
- (id)_legibilitySettingsWithParameters:(id)arg1;
- (void)_updateLabel;
- (id)_labelImageParameters;
- (void)invalidateLabelLayoutGeometry;
- (void)_updateAdaptiveColors;
- (id)_labelImage;
- (id)_iconImageView;
- (struct CGPoint)_centerForCloseBoxRelativeToVisibleImageFrame:(struct CGRect)arg1;
- (struct CGPoint)_centerForCloseBox;
- (struct CGRect)_frameForAccessoryView;
- (struct CGRect)_frameForUpdatedMarkWithLabelFrame:(struct CGRect)arg1;
- (struct CGRect)_frameForLabel;
- (CGFloat)_labelVerticalOffset; // Huzzah!
- (struct CGRect)_frameForImageView;
- (void)layoutSubviews;
- (void)setUpdatedMarkHidden:(BOOL)arg1;
- (void)setLabelHidden:(BOOL)arg1;
- (void)_applyIconLabelAlpha:(CGFloat)arg1;
- (void)_applyIconAccessoryAlpha:(CGFloat)arg1;
- (void)_applyIconImageAlpha:(CGFloat)arg1;
- (void)setIconImageAndAccessoryAlpha:(CGFloat)arg1;
- (struct CGSize)iconImageVisibleSize;
- (struct CGPoint)iconImageCenter;
- (struct CGRect)iconImageFrame;
- (id)iconImageSnapshot;
- (void)swapInIcon:(id)arg1;
- (void)_setIcon:(id)arg1 animated:(BOOL)arg2;
- (void)setPaused:(BOOL)arg1;
- (void)dealloc;
- (id)initWithDefaultSize;

- (BOOL)isDragging; // iOS 11

// iOS Blocks

@property (nonatomic, retain) UIView *widgetView;
- (void)loadWidget;


@end

