/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "SBIconListLayoutDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableSet, SBIcon, SBIconListModel, SBIconViewMap;

@interface SBIconListView : UIView
{
    SBIconListModel *_model;
    SBIconViewMap *_viewMap;
    int _orientation;
    float _statusBarHeight;
    SBIcon *_bouncedIcon;
    NSMutableArray *_removedIcons;
    NSArray *_rotationContainers;
    unsigned int _needsLayout:1;
    unsigned int _rotating:1;
    UIView *_fadeView;
    BOOL _purged;
    NSMutableSet *_notShownIconViews;
    BOOL _isEditing;
    id <SBIconListLayoutDelegate> _layoutDelegate;
    struct CGRect _wallpaperRelativeFrame;
}

+ (unsigned int)maxVisibleIcons;
+ (unsigned int)maxIcons;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)arg1;
+ (unsigned int)maxVisibleIconRowsInterfaceOrientation:(int)arg1;
+ (unsigned int)iconRowsForInterfaceOrientation:(int)arg1;
+ (int)rotationAnchor;
@property(nonatomic, retain) id <SBIconListLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) struct CGRect wallpaperRelativeFrame; // @synthesize wallpaperRelativeFrame=_wallpaperRelativeFrame;
@property(nonatomic) float statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(nonatomic) BOOL purged; // @synthesize purged=_purged;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_isEditing;
- (void)_sendLayoutDelegateLayoutInvalidated;
- (void)_sendLayoutDelegateWouldHaveMovedIcon:(id)arg1;
- (void)cleanupAfterRotation;
- (void)performRotationWithDuration:(double)arg1;
- (void)prepareToRotateToInterfaceOrientation:(int)arg1;
- (unsigned int)rowAtPoint:(struct CGPoint)arg1;
- (unsigned int)columnAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (float)verticalIconPadding;
- (float)horizontalIconPadding;
- (float)horizontalBumpForColumn:(unsigned int)arg1;
- (float)sideIconInset;
- (float)bottomIconInset;
- (float)topIconInset;
- (id)bouncedIcon;
- (void)setBouncedIcon:(id)arg1;
- (BOOL)isDock;
- (void)enumerateIconViewsUsingBlock:(id)arg1;
- (void)enumerateIconsUsingBlock:(id)arg1;
- (void)_updateEditingStateForIcons:(id)arg1 animated:(BOOL)arg2;
- (void)updateEditingStateAnimated:(BOOL)arg1;
- (void)showIconImagesFromColumn:(int)arg1 toColumn:(int)arg2 totalColumns:(int)arg3 allowAnimations:(BOOL)arg4;
- (void)showAllIcons;
- (id)iconAtPoint:(CGPoint)arg1 index:(unsigned int *)arg2 proposedOrder:(int *)arg3 grabbedIcon:(id)arg4;
- (id)iconAtPoint:(CGPoint)arg1 index:(unsigned int *)arg2;
- (void)layoutIconsIfNeeded:(CGFloat)arg1 domino:(BOOL)arg2;
- (void)layoutIconsNow;
- (void)setIconsNeedLayout;
- (void)setFrame:(struct CGRect)arg1;
- (unsigned int)indexOfIcon:(id)arg1;
- (struct SBIconCoordinate)coordinateForIconAtIndex:(unsigned int)arg1;
- (struct SBIconCoordinate)coordinateForIcon:(id)arg1;
- (id)viewForIcon:(id)arg1; // I like you.
- (struct CGPoint)centerForIconCoordinate:(struct SBIconCoordinate)arg1;
- (struct CGPoint)centerForIcon:(id)arg1;
- (struct CGPoint)originForIcon:(id)arg1;
- (struct CGPoint)originForIconAtIndex:(unsigned int)arg1;
- (struct CGSize)defaultIconSize;
- (void)removeAllIconAnimations;
- (void)setAlphaForAllIcons:(float)arg1;
- (void)removeIcon:(id)arg1;
- (void)removeIconAtIndex:(unsigned int)arg1;
- (id)removedIcons;
- (id)insertIcon:(id)arg1 atIndex:(unsigned int)arg2 moveNow:(BOOL)arg3;
- (id)insertIcon:(id)arg1 /* SBIcon I'd assume, need to verify */ atIndex:(unsigned int)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (id)placeIcon:(id)arg1 atIndex:(unsigned int)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_layoutIcon:(id)arg1 atIndex:(unsigned int)arg2 createViewNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_popIconView:(id)arg1;
- (unsigned int)firstFreeSlotOrLastSlotIndexForType:(int)arg1;
- (unsigned int)firstFreeSlotOrLastSlotIndex;
- (unsigned int)firstFreeSlotIndexForType:(int)arg1;
- (unsigned int)firstFreeSlotIndex;
- (BOOL)containsIcon:(id)arg1;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (NSArray*)visibleIcons;
- (NSArray*)icons;
- (BOOL)compactIcons:(BOOL)arg1;
- (unsigned int)rowForIcon:(id)arg1;
- (id)description;
- (struct SBIconCoordinate)iconCoordinateForIndex:(unsigned int)arg1 forOrientation:(int)arg2;
- (unsigned int)indexForCoordinate:(struct SBIconCoordinate)arg1 forOrientation:(int)arg2;
- (int)iconLocation;
- (unsigned int)iconRowsForSpacingCalculation;
- (unsigned int)iconsInRowForSpacingCalculation;
- (unsigned int)iconColumnsForCurrentOrientation;
- (unsigned int)iconRowsForCurrentOrientation;
- (struct CGPoint)_wallpaperRelativeIconCenterForIconView:(id)arg1;
- (Class)baseIconViewClass;
- (id)viewMap;
- (id)model; // SBIconListModel
- (void)setModel:(id)arg1;
- (void)dealloc;
- (id)initWithModel:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3; // One of these is made per page of SB
- (id)init;
- (Class)modelClass;

@end

