/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIScrollView.h>
#import <UIKit/UIGestureRecognizer.h>
 
#import "SBIconScrollViewDelegate-Protocol.h"

@interface SBIconScrollView : UIScrollView <UIGestureRecognizerDelegate>
{
}

- (void)setContentOffset:(CGPoint)arg1;
- (BOOL)_scrollsToMakeFirstResponderVisible;
- (BOOL)cancelTouchTracking;

// Remaining properties
@property(assign,nonatomic) id <SBIconScrollViewDelegate> delegate;

// iOS Blocks

-(void)handlePinchGesture:(UIPinchGestureRecognizer*)pinch;

@end

