/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBInteractionPassThroughView.h"

@class SBIconImageView, UIView, _SBAnimatableCorneredView;

@interface SBIconImageCrossfadeView : SBInteractionPassThroughView
{
    _SBAnimatableCorneredView *_containerView;
    SBIconImageView *_imageView;
    UIView *_crossfadeView;
    float _crossfadeFraction;
    float _containerScaleX;
    float _containerScaleY;
    BOOL _masksCorners;
    BOOL _performsTrueCrossfade;
    struct CGPoint _stretchAnchorPoint;
}

@property(nonatomic) struct CGPoint stretchAnchorPoint; // @synthesize stretchAnchorPoint=_stretchAnchorPoint;
@property(nonatomic) BOOL performsTrueCrossfade; // @synthesize performsTrueCrossfade=_performsTrueCrossfade;
@property(nonatomic) BOOL masksCorners; // @synthesize masksCorners=_masksCorners;
- (void)_updateCornerMask;
- (void)cleanup;
- (void)setMorphFraction:(float)arg1;
- (void)setFadeFraction:(float)arg1;
- (void)layoutSubviews;
- (void)prepareGeometry;
- (void)dealloc;
- (id)initWithImageView:(id)arg1 crossfadeView:(id)arg2;

@end

