/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@protocol SBSystemLocalNotificationAlertDelegate <NSObject>
- (void)systemLocalNotificationAlertShouldLaunch:(id)systemLocalNotificationAlert forApplication:(id)application;
@optional
- (void)systemLocalNotificationAlertShouldSnooze:(id)systemLocalNotificationAlert forApplication:(id)application;
@end

