/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@protocol SBWindowContextHostManagerDelegate <NSObject>

@optional
- (BOOL)windowContextHostManager:(id)arg1 shouldEnableContextHostingForRequester:(id)arg2 priority:(int)arg3;
- (id)windowContextHostManager:(id)arg1 overrideRequester:(id)arg2;
@end

